export const myProjects = [
  {
    title: 'A-Nofa-Trano',
    desc: 'A real estate rental platform in Madagascar connecting tenants and property owners safely through a centralized Admin. Prevents scams via strict property validation and a triangular messaging system.',
    subdesc:
      'Full-stack app built with React.js (Atomic Design), Node.js, Express.js (MVC), Prisma ORM, PostgreSQL and Docker. Three-role system: Tenant, Admin and Landlord.',
    href: 'https://github.com/ChristianMDG/A_nofa_trano',
    liveDemo: 'https://github.com/ChristianMDG/A_nofa_trano',
    placeholder: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    logo: '/assets/images/project-logo1.png',
    logoStyle: {
      backgroundColor: '#1a0a2e',
      border: '0.2px solid #6c2bd9',
      boxShadow: '0px 0px 60px 0px #6c2bd94D',
    },
    spotlight: '/assets/images/spotlight1.png',
    tags: [
      { id: 1, name: 'React.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { id: 2, name: 'TypeScript', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
      { id: 3, name: 'Node.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { id: 4, name: 'PostgreSQL', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
      { id: 5, name: 'Docker', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
      { id: 6, name: 'Prisma', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg' },
    ],
  },
  {
    title: 'Planifeo App',
    desc: 'A full-stack planning and task management application with a clean dashboard for organizing projects and schedules, with authentication and a REST API backend.',
    subdesc:
      'React + Vite frontend, Node.js + Express.js backend, Prisma ORM connected to PostgreSQL. Frontend deployed on Vercel, backend on Render.',
    href: 'https://github.com/ChristianMDG/Planifeo_frontend',
    liveDemo: 'https://planifeo.vercel.app/',
    placeholder: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
    logo: '/assets/images/project-logo2.png',
    logoStyle: {
      backgroundColor: '#0d1f2d',
      border: '0.2px solid #17293E',
      boxShadow: '0px 0px 60px 0px #2F6DB54D',
    },
    spotlight: '/assets/images/spotlight2.png',
    tags: [
      { id: 1, name: 'React.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { id: 2, name: 'Node.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { id: 3, name: 'Express.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
      { id: 4, name: 'PostgreSQL', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
      { id: 5, name: 'Prisma', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg' },
    ],
  },
  {
    title: 'Traffic-AI',
    desc: 'A data science project that predicts road traffic volume using temporal and weather data. Anticipates congestion levels in urban areas using machine learning models.',
    subdesc:
      'Built with Python, Streamlit and Pandas. ML models trained on historical traffic datasets. Fully deployed and interactive on Streamlit Cloud.',
    href: 'https://github.com/ChristianMDG/Traffic-Ai',
    liveDemo: 'https://traffic-ai-3szvrge57wehtps7ghcb2d.streamlit.app/',
    placeholder: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=800&q=80',
    logo: '/assets/images/project-logo3.png',
    logoStyle: {
      backgroundColor: '#1C1A43',
      border: '0.2px solid #252262',
      boxShadow: '0px 0px 60px 0px #635BFF4D',
    },
    spotlight: '/assets/images/spotlight3.png',
    tags: [
      { id: 1, name: 'Python', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
      { id: 2, name: 'Pandas', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
      { id: 3, name: 'Jupyter', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg' },
      { id: 4, name: 'Streamlit', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/streamlit/streamlit-original.svg' },
    ],
  },
  {
    title: 'PERN Auth',
    desc: 'A secure authentication system demonstrating JWT concepts, HTTP-only cookies, and session management. A practical deep-dive into fullstack security patterns.',
    subdesc:
      'Built with the full PERN stack (PostgreSQL, Express.js, React, Node.js). Implements JWT token generation, refresh tokens, protected routes and secure cookie handling.',
    href: 'https://github.com/ChristianMDG/Pern_Auth',
    liveDemo: 'https://github.com/ChristianMDG/Pern_Auth',
    placeholder: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80',
    logo: '/assets/images/project-logo5.png',
    logoStyle: {
      backgroundColor: '#0f2027',
      border: '0.2px solid #00b4d8',
      boxShadow: '0px 0px 60px 0px #00b4d84D',
    },
    spotlight: '/assets/images/spotlight5.png',
    tags: [
      { id: 1, name: 'React.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { id: 2, name: 'Node.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { id: 3, name: 'Express.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
      { id: 4, name: 'PostgreSQL', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
      { id: 5, name: 'JavaScript', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    ],
  },
  {
    title: 'Vidy-Boky',
    desc: 'A Java Spring Boot bookstore and library management system with a full entity model. Manages books, authors, orders, stock movements and digital formats.',
    subdesc:
      'Built with Spring Boot, Gradle, JPA/Hibernate, Neon cloud PostgreSQL. Features 16 MVP entities with UUID primary keys, soft deletes, and role-based access.',
    href: 'https://github.com/ChristianMDG/vidy-boky',
    liveDemo: 'https://github.com/ChristianMDG/vidy-boky',
    placeholder: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&q=80',
    logo: '/assets/images/project-logo1.png',
    logoStyle: {
      backgroundColor: '#1a2f1a',
      border: '0.2px solid #2d8a2d',
      boxShadow: '0px 0px 60px 0px #2d8a2d4D',
    },
    spotlight: '/assets/images/spotlight1.png',
    tags: [
      { id: 1, name: 'Java', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
      { id: 2, name: 'Spring Boot', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg' },
      { id: 3, name: 'PostgreSQL', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
      { id: 4, name: 'Gradle', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gradle/gradle-original.svg' },
    ],
  },
  {
    title: 'Christian Portfolio',
    desc: 'My personal developer portfolio showcasing my skills, projects and professional journey. Features a retro TV project viewer, animated hero, and smooth section transitions.',
    subdesc:
      'Built with React, TailwindCSS and Framer Motion. Fully responsive with CRT-style animations, custom fonts, and a clean dark aesthetic. Deployed on Vercel.',
    href: 'https://github.com/ChristianMDG/Christian_Portfolio',
    liveDemo: 'https://christian-portfolio-u9jz.vercel.app/',
    placeholder: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80',
    logo: '/assets/images/project-logo2.png',
    logoStyle: {
      backgroundColor: '#1a1a1a',
      border: '0.2px solid #f0f0f0',
      boxShadow: '0px 0px 60px 0px rgba(255,255,255,0.1)',
    },
    spotlight: '/assets/images/spotlight2.png',
    tags: [
      { id: 1, name: 'React.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { id: 2, name: 'TailwindCSS', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
      { id: 3, name: 'Vite', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vitejs/vitejs-original.svg' },
      { id: 4, name: 'JavaScript', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    ],
  },
  {
    title: 'Planifeo Backend',
    desc: 'The REST API backend of the Planifeo planning app. Provides full CRUD endpoints, JWT-based authentication, and database management for tasks and projects.',
    subdesc:
      'Built with Node.js, Express.js and Prisma ORM connected to PostgreSQL. Clean MVC architecture with organized routes, middlewares and controllers. Deployed on Render.',
    href: 'https://github.com/ChristianMDG/Planifeo_backend',
    liveDemo: 'https://github.com/ChristianMDG/Planifeo_backend',
    placeholder: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    logo: '/assets/images/project-logo3.png',
    logoStyle: {
      backgroundColor: '#0d1117',
      border: '0.2px solid #30a14e',
      boxShadow: '0px 0px 60px 0px #30a14e4D',
    },
    spotlight: '/assets/images/spotlight3.png',
    tags: [
      { id: 1, name: 'Node.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
      { id: 2, name: 'Express.js', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
      { id: 3, name: 'Prisma', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg' },
      { id: 4, name: 'PostgreSQL', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
      { id: 5, name: 'JavaScript', path: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    ],
  },
];